/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser";

export type * from "../models";
export type * from "./prismaNamespace";

export const Decimal = runtime.Decimal;

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (
    secret: never,
  ) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (
    secret: never,
  ) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (
    secret: never,
  ) => typeof runtime.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull;

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull;

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull;

export const ModelName = {
  User: "User",
  Session: "Session",
  Account: "Account",
  Verification: "Verification",
  OrgUser: "OrgUser",
  Tag: "Tag",
  Workspace: "Workspace",
  Category: "Category",
  Priority: "Priority",
  Status: "Status",
  Task: "Task",
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable",
} as const);

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel];

export const UserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  emailVerified: "emailVerified",
  image: "image",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  role: "role",
} as const;

export type UserScalarFieldEnum =
  (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum];

export const SessionScalarFieldEnum = {
  id: "id",
  expiresAt: "expiresAt",
  token: "token",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  ipAddress: "ipAddress",
  userAgent: "userAgent",
  userId: "userId",
} as const;

export type SessionScalarFieldEnum =
  (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum];

export const AccountScalarFieldEnum = {
  id: "id",
  accountId: "accountId",
  providerId: "providerId",
  userId: "userId",
  accessToken: "accessToken",
  refreshToken: "refreshToken",
  idToken: "idToken",
  accessTokenExpiresAt: "accessTokenExpiresAt",
  refreshTokenExpiresAt: "refreshTokenExpiresAt",
  scope: "scope",
  password: "password",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export type AccountScalarFieldEnum =
  (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum];

export const VerificationScalarFieldEnum = {
  id: "id",
  identifier: "identifier",
  value: "value",
  expiresAt: "expiresAt",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export type VerificationScalarFieldEnum =
  (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum];

export const OrgUserScalarFieldEnum = {
  userId: "userId",
} as const;

export type OrgUserScalarFieldEnum =
  (typeof OrgUserScalarFieldEnum)[keyof typeof OrgUserScalarFieldEnum];

export const TagScalarFieldEnum = {
  id: "id",
  name: "name",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  createdById: "createdById",
} as const;

export type TagScalarFieldEnum =
  (typeof TagScalarFieldEnum)[keyof typeof TagScalarFieldEnum];

export const WorkspaceScalarFieldEnum = {
  id: "id",
  name: "name",
  description: "description",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  createdById: "createdById",
} as const;

export type WorkspaceScalarFieldEnum =
  (typeof WorkspaceScalarFieldEnum)[keyof typeof WorkspaceScalarFieldEnum];

export const CategoryScalarFieldEnum = {
  id: "id",
  name: "name",
  description: "description",
  order: "order",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  parentId: "parentId",
  workspaceId: "workspaceId",
} as const;

export type CategoryScalarFieldEnum =
  (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum];

export const PriorityScalarFieldEnum = {
  id: "id",
  name: "name",
  code: "code",
  order: "order",
  group: "group",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  workspaceId: "workspaceId",
} as const;

export type PriorityScalarFieldEnum =
  (typeof PriorityScalarFieldEnum)[keyof typeof PriorityScalarFieldEnum];

export const StatusScalarFieldEnum = {
  id: "id",
  name: "name",
  order: "order",
  code: "code",
  group: "group",
  isCompletion: "isCompletion",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  workspaceId: "workspaceId",
} as const;

export type StatusScalarFieldEnum =
  (typeof StatusScalarFieldEnum)[keyof typeof StatusScalarFieldEnum];

export const TaskScalarFieldEnum = {
  id: "id",
  title: "title",
  description: "description",
  is_archived: "is_archived",
  archive_on_completion: "archive_on_completion",
  start_date: "start_date",
  end_date: "end_date",
  estimated_start: "estimated_start",
  estimated_end: "estimated_end",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  createdById: "createdById",
  parentId: "parentId",
  categoryId: "categoryId",
  priorityId: "priorityId",
  statusId: "statusId",
} as const;

export type TaskScalarFieldEnum =
  (typeof TaskScalarFieldEnum)[keyof typeof TaskScalarFieldEnum];

export const SortOrder = {
  asc: "asc",
  desc: "desc",
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const QueryMode = {
  default: "default",
  insensitive: "insensitive",
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];

export const NullsOrder = {
  first: "first",
  last: "last",
} as const;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];
