/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `OrgUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model OrgUser
 *
 */
export type OrgUserModel =
  runtime.Types.Result.DefaultSelection<Prisma.$OrgUserPayload>;

export type AggregateOrgUser = {
  _count: OrgUserCountAggregateOutputType | null;
  _min: OrgUserMinAggregateOutputType | null;
  _max: OrgUserMaxAggregateOutputType | null;
};

export type OrgUserMinAggregateOutputType = {
  userId: string | null;
};

export type OrgUserMaxAggregateOutputType = {
  userId: string | null;
};

export type OrgUserCountAggregateOutputType = {
  userId: number;
  _all: number;
};

export type OrgUserMinAggregateInputType = {
  userId?: true;
};

export type OrgUserMaxAggregateInputType = {
  userId?: true;
};

export type OrgUserCountAggregateInputType = {
  userId?: true;
  _all?: true;
};

export type OrgUserAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which OrgUser to aggregate.
   */
  where?: Prisma.OrgUserWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OrgUsers to fetch.
   */
  orderBy?:
    | Prisma.OrgUserOrderByWithRelationInput
    | Prisma.OrgUserOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.OrgUserWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OrgUsers from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OrgUsers.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned OrgUsers
   **/
  _count?: true | OrgUserCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: OrgUserMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: OrgUserMaxAggregateInputType;
};

export type GetOrgUserAggregateType<T extends OrgUserAggregateArgs> = {
  [P in keyof T & keyof AggregateOrgUser]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrgUser[P]>
    : Prisma.GetScalarType<T[P], AggregateOrgUser[P]>;
};

export type OrgUserGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.OrgUserWhereInput;
  orderBy?:
    | Prisma.OrgUserOrderByWithAggregationInput
    | Prisma.OrgUserOrderByWithAggregationInput[];
  by: Prisma.OrgUserScalarFieldEnum[] | Prisma.OrgUserScalarFieldEnum;
  having?: Prisma.OrgUserScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: OrgUserCountAggregateInputType | true;
  _min?: OrgUserMinAggregateInputType;
  _max?: OrgUserMaxAggregateInputType;
};

export type OrgUserGroupByOutputType = {
  userId: string;
  _count: OrgUserCountAggregateOutputType | null;
  _min: OrgUserMinAggregateOutputType | null;
  _max: OrgUserMaxAggregateOutputType | null;
};

type GetOrgUserGroupByPayload<T extends OrgUserGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<OrgUserGroupByOutputType, T["by"]> & {
        [P in keyof T & keyof OrgUserGroupByOutputType]: P extends "_count"
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrgUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrgUserGroupByOutputType[P]>;
      }
    >
  >;

export type OrgUserWhereInput = {
  AND?: Prisma.OrgUserWhereInput | Prisma.OrgUserWhereInput[];
  OR?: Prisma.OrgUserWhereInput[];
  NOT?: Prisma.OrgUserWhereInput | Prisma.OrgUserWhereInput[];
  userId?: Prisma.StringFilter<"OrgUser"> | string;
  id?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  tags?: Prisma.TagListRelationFilter;
  workspaces?: Prisma.WorkspaceListRelationFilter;
  tasks?: Prisma.TaskListRelationFilter;
};

export type OrgUserOrderByWithRelationInput = {
  userId?: Prisma.SortOrder;
  id?: Prisma.UserOrderByWithRelationInput;
  tags?: Prisma.TagOrderByRelationAggregateInput;
  workspaces?: Prisma.WorkspaceOrderByRelationAggregateInput;
  tasks?: Prisma.TaskOrderByRelationAggregateInput;
};

export type OrgUserWhereUniqueInput = Prisma.AtLeast<
  {
    userId?: string;
    AND?: Prisma.OrgUserWhereInput | Prisma.OrgUserWhereInput[];
    OR?: Prisma.OrgUserWhereInput[];
    NOT?: Prisma.OrgUserWhereInput | Prisma.OrgUserWhereInput[];
    id?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    tags?: Prisma.TagListRelationFilter;
    workspaces?: Prisma.WorkspaceListRelationFilter;
    tasks?: Prisma.TaskListRelationFilter;
  },
  "userId"
>;

export type OrgUserOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder;
  _count?: Prisma.OrgUserCountOrderByAggregateInput;
  _max?: Prisma.OrgUserMaxOrderByAggregateInput;
  _min?: Prisma.OrgUserMinOrderByAggregateInput;
};

export type OrgUserScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.OrgUserScalarWhereWithAggregatesInput
    | Prisma.OrgUserScalarWhereWithAggregatesInput[];
  OR?: Prisma.OrgUserScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.OrgUserScalarWhereWithAggregatesInput
    | Prisma.OrgUserScalarWhereWithAggregatesInput[];
  userId?: Prisma.StringWithAggregatesFilter<"OrgUser"> | string;
};

export type OrgUserCreateInput = {
  id: Prisma.UserCreateNestedOneWithoutOrgUserInput;
  tags?: Prisma.TagCreateNestedManyWithoutCreatedByInput;
  workspaces?: Prisma.WorkspaceCreateNestedManyWithoutCreatedByInput;
  tasks?: Prisma.TaskCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserUncheckedCreateInput = {
  userId: string;
  tags?: Prisma.TagUncheckedCreateNestedManyWithoutCreatedByInput;
  workspaces?: Prisma.WorkspaceUncheckedCreateNestedManyWithoutCreatedByInput;
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserUpdateInput = {
  id?: Prisma.UserUpdateOneRequiredWithoutOrgUserNestedInput;
  tags?: Prisma.TagUpdateManyWithoutCreatedByNestedInput;
  workspaces?: Prisma.WorkspaceUpdateManyWithoutCreatedByNestedInput;
  tasks?: Prisma.TaskUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  tags?: Prisma.TagUncheckedUpdateManyWithoutCreatedByNestedInput;
  workspaces?: Prisma.WorkspaceUncheckedUpdateManyWithoutCreatedByNestedInput;
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserCreateManyInput = {
  userId: string;
};

export type OrgUserUpdateManyMutationInput = {};

export type OrgUserUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type OrgUserNullableScalarRelationFilter = {
  is?: Prisma.OrgUserWhereInput | null;
  isNot?: Prisma.OrgUserWhereInput | null;
};

export type OrgUserCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
};

export type OrgUserMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
};

export type OrgUserMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
};

export type OrgUserScalarRelationFilter = {
  is?: Prisma.OrgUserWhereInput;
  isNot?: Prisma.OrgUserWhereInput;
};

export type OrgUserCreateNestedOneWithoutIdInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutIdInput,
    Prisma.OrgUserUncheckedCreateWithoutIdInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutIdInput;
  connect?: Prisma.OrgUserWhereUniqueInput;
};

export type OrgUserUncheckedCreateNestedOneWithoutIdInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutIdInput,
    Prisma.OrgUserUncheckedCreateWithoutIdInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutIdInput;
  connect?: Prisma.OrgUserWhereUniqueInput;
};

export type OrgUserUpdateOneWithoutIdNestedInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutIdInput,
    Prisma.OrgUserUncheckedCreateWithoutIdInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutIdInput;
  upsert?: Prisma.OrgUserUpsertWithoutIdInput;
  disconnect?: Prisma.OrgUserWhereInput | boolean;
  delete?: Prisma.OrgUserWhereInput | boolean;
  connect?: Prisma.OrgUserWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.OrgUserUpdateToOneWithWhereWithoutIdInput,
      Prisma.OrgUserUpdateWithoutIdInput
    >,
    Prisma.OrgUserUncheckedUpdateWithoutIdInput
  >;
};

export type OrgUserUncheckedUpdateOneWithoutIdNestedInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutIdInput,
    Prisma.OrgUserUncheckedCreateWithoutIdInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutIdInput;
  upsert?: Prisma.OrgUserUpsertWithoutIdInput;
  disconnect?: Prisma.OrgUserWhereInput | boolean;
  delete?: Prisma.OrgUserWhereInput | boolean;
  connect?: Prisma.OrgUserWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.OrgUserUpdateToOneWithWhereWithoutIdInput,
      Prisma.OrgUserUpdateWithoutIdInput
    >,
    Prisma.OrgUserUncheckedUpdateWithoutIdInput
  >;
};

export type OrgUserCreateNestedOneWithoutTagsInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutTagsInput,
    Prisma.OrgUserUncheckedCreateWithoutTagsInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutTagsInput;
  connect?: Prisma.OrgUserWhereUniqueInput;
};

export type OrgUserUpdateOneRequiredWithoutTagsNestedInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutTagsInput,
    Prisma.OrgUserUncheckedCreateWithoutTagsInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutTagsInput;
  upsert?: Prisma.OrgUserUpsertWithoutTagsInput;
  connect?: Prisma.OrgUserWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.OrgUserUpdateToOneWithWhereWithoutTagsInput,
      Prisma.OrgUserUpdateWithoutTagsInput
    >,
    Prisma.OrgUserUncheckedUpdateWithoutTagsInput
  >;
};

export type OrgUserCreateNestedOneWithoutWorkspacesInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutWorkspacesInput,
    Prisma.OrgUserUncheckedCreateWithoutWorkspacesInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutWorkspacesInput;
  connect?: Prisma.OrgUserWhereUniqueInput;
};

export type OrgUserUpdateOneRequiredWithoutWorkspacesNestedInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutWorkspacesInput,
    Prisma.OrgUserUncheckedCreateWithoutWorkspacesInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutWorkspacesInput;
  upsert?: Prisma.OrgUserUpsertWithoutWorkspacesInput;
  connect?: Prisma.OrgUserWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.OrgUserUpdateToOneWithWhereWithoutWorkspacesInput,
      Prisma.OrgUserUpdateWithoutWorkspacesInput
    >,
    Prisma.OrgUserUncheckedUpdateWithoutWorkspacesInput
  >;
};

export type OrgUserCreateNestedOneWithoutTasksInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutTasksInput,
    Prisma.OrgUserUncheckedCreateWithoutTasksInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutTasksInput;
  connect?: Prisma.OrgUserWhereUniqueInput;
};

export type OrgUserUpdateOneRequiredWithoutTasksNestedInput = {
  create?: Prisma.XOR<
    Prisma.OrgUserCreateWithoutTasksInput,
    Prisma.OrgUserUncheckedCreateWithoutTasksInput
  >;
  connectOrCreate?: Prisma.OrgUserCreateOrConnectWithoutTasksInput;
  upsert?: Prisma.OrgUserUpsertWithoutTasksInput;
  connect?: Prisma.OrgUserWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.OrgUserUpdateToOneWithWhereWithoutTasksInput,
      Prisma.OrgUserUpdateWithoutTasksInput
    >,
    Prisma.OrgUserUncheckedUpdateWithoutTasksInput
  >;
};

export type OrgUserCreateWithoutIdInput = {
  tags?: Prisma.TagCreateNestedManyWithoutCreatedByInput;
  workspaces?: Prisma.WorkspaceCreateNestedManyWithoutCreatedByInput;
  tasks?: Prisma.TaskCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserUncheckedCreateWithoutIdInput = {
  tags?: Prisma.TagUncheckedCreateNestedManyWithoutCreatedByInput;
  workspaces?: Prisma.WorkspaceUncheckedCreateNestedManyWithoutCreatedByInput;
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserCreateOrConnectWithoutIdInput = {
  where: Prisma.OrgUserWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.OrgUserCreateWithoutIdInput,
    Prisma.OrgUserUncheckedCreateWithoutIdInput
  >;
};

export type OrgUserUpsertWithoutIdInput = {
  update: Prisma.XOR<
    Prisma.OrgUserUpdateWithoutIdInput,
    Prisma.OrgUserUncheckedUpdateWithoutIdInput
  >;
  create: Prisma.XOR<
    Prisma.OrgUserCreateWithoutIdInput,
    Prisma.OrgUserUncheckedCreateWithoutIdInput
  >;
  where?: Prisma.OrgUserWhereInput;
};

export type OrgUserUpdateToOneWithWhereWithoutIdInput = {
  where?: Prisma.OrgUserWhereInput;
  data: Prisma.XOR<
    Prisma.OrgUserUpdateWithoutIdInput,
    Prisma.OrgUserUncheckedUpdateWithoutIdInput
  >;
};

export type OrgUserUpdateWithoutIdInput = {
  tags?: Prisma.TagUpdateManyWithoutCreatedByNestedInput;
  workspaces?: Prisma.WorkspaceUpdateManyWithoutCreatedByNestedInput;
  tasks?: Prisma.TaskUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserUncheckedUpdateWithoutIdInput = {
  tags?: Prisma.TagUncheckedUpdateManyWithoutCreatedByNestedInput;
  workspaces?: Prisma.WorkspaceUncheckedUpdateManyWithoutCreatedByNestedInput;
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserCreateWithoutTagsInput = {
  id: Prisma.UserCreateNestedOneWithoutOrgUserInput;
  workspaces?: Prisma.WorkspaceCreateNestedManyWithoutCreatedByInput;
  tasks?: Prisma.TaskCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserUncheckedCreateWithoutTagsInput = {
  userId: string;
  workspaces?: Prisma.WorkspaceUncheckedCreateNestedManyWithoutCreatedByInput;
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserCreateOrConnectWithoutTagsInput = {
  where: Prisma.OrgUserWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.OrgUserCreateWithoutTagsInput,
    Prisma.OrgUserUncheckedCreateWithoutTagsInput
  >;
};

export type OrgUserUpsertWithoutTagsInput = {
  update: Prisma.XOR<
    Prisma.OrgUserUpdateWithoutTagsInput,
    Prisma.OrgUserUncheckedUpdateWithoutTagsInput
  >;
  create: Prisma.XOR<
    Prisma.OrgUserCreateWithoutTagsInput,
    Prisma.OrgUserUncheckedCreateWithoutTagsInput
  >;
  where?: Prisma.OrgUserWhereInput;
};

export type OrgUserUpdateToOneWithWhereWithoutTagsInput = {
  where?: Prisma.OrgUserWhereInput;
  data: Prisma.XOR<
    Prisma.OrgUserUpdateWithoutTagsInput,
    Prisma.OrgUserUncheckedUpdateWithoutTagsInput
  >;
};

export type OrgUserUpdateWithoutTagsInput = {
  id?: Prisma.UserUpdateOneRequiredWithoutOrgUserNestedInput;
  workspaces?: Prisma.WorkspaceUpdateManyWithoutCreatedByNestedInput;
  tasks?: Prisma.TaskUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserUncheckedUpdateWithoutTagsInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  workspaces?: Prisma.WorkspaceUncheckedUpdateManyWithoutCreatedByNestedInput;
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserCreateWithoutWorkspacesInput = {
  id: Prisma.UserCreateNestedOneWithoutOrgUserInput;
  tags?: Prisma.TagCreateNestedManyWithoutCreatedByInput;
  tasks?: Prisma.TaskCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserUncheckedCreateWithoutWorkspacesInput = {
  userId: string;
  tags?: Prisma.TagUncheckedCreateNestedManyWithoutCreatedByInput;
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserCreateOrConnectWithoutWorkspacesInput = {
  where: Prisma.OrgUserWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.OrgUserCreateWithoutWorkspacesInput,
    Prisma.OrgUserUncheckedCreateWithoutWorkspacesInput
  >;
};

export type OrgUserUpsertWithoutWorkspacesInput = {
  update: Prisma.XOR<
    Prisma.OrgUserUpdateWithoutWorkspacesInput,
    Prisma.OrgUserUncheckedUpdateWithoutWorkspacesInput
  >;
  create: Prisma.XOR<
    Prisma.OrgUserCreateWithoutWorkspacesInput,
    Prisma.OrgUserUncheckedCreateWithoutWorkspacesInput
  >;
  where?: Prisma.OrgUserWhereInput;
};

export type OrgUserUpdateToOneWithWhereWithoutWorkspacesInput = {
  where?: Prisma.OrgUserWhereInput;
  data: Prisma.XOR<
    Prisma.OrgUserUpdateWithoutWorkspacesInput,
    Prisma.OrgUserUncheckedUpdateWithoutWorkspacesInput
  >;
};

export type OrgUserUpdateWithoutWorkspacesInput = {
  id?: Prisma.UserUpdateOneRequiredWithoutOrgUserNestedInput;
  tags?: Prisma.TagUpdateManyWithoutCreatedByNestedInput;
  tasks?: Prisma.TaskUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserUncheckedUpdateWithoutWorkspacesInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  tags?: Prisma.TagUncheckedUpdateManyWithoutCreatedByNestedInput;
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserCreateWithoutTasksInput = {
  id: Prisma.UserCreateNestedOneWithoutOrgUserInput;
  tags?: Prisma.TagCreateNestedManyWithoutCreatedByInput;
  workspaces?: Prisma.WorkspaceCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserUncheckedCreateWithoutTasksInput = {
  userId: string;
  tags?: Prisma.TagUncheckedCreateNestedManyWithoutCreatedByInput;
  workspaces?: Prisma.WorkspaceUncheckedCreateNestedManyWithoutCreatedByInput;
};

export type OrgUserCreateOrConnectWithoutTasksInput = {
  where: Prisma.OrgUserWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.OrgUserCreateWithoutTasksInput,
    Prisma.OrgUserUncheckedCreateWithoutTasksInput
  >;
};

export type OrgUserUpsertWithoutTasksInput = {
  update: Prisma.XOR<
    Prisma.OrgUserUpdateWithoutTasksInput,
    Prisma.OrgUserUncheckedUpdateWithoutTasksInput
  >;
  create: Prisma.XOR<
    Prisma.OrgUserCreateWithoutTasksInput,
    Prisma.OrgUserUncheckedCreateWithoutTasksInput
  >;
  where?: Prisma.OrgUserWhereInput;
};

export type OrgUserUpdateToOneWithWhereWithoutTasksInput = {
  where?: Prisma.OrgUserWhereInput;
  data: Prisma.XOR<
    Prisma.OrgUserUpdateWithoutTasksInput,
    Prisma.OrgUserUncheckedUpdateWithoutTasksInput
  >;
};

export type OrgUserUpdateWithoutTasksInput = {
  id?: Prisma.UserUpdateOneRequiredWithoutOrgUserNestedInput;
  tags?: Prisma.TagUpdateManyWithoutCreatedByNestedInput;
  workspaces?: Prisma.WorkspaceUpdateManyWithoutCreatedByNestedInput;
};

export type OrgUserUncheckedUpdateWithoutTasksInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  tags?: Prisma.TagUncheckedUpdateManyWithoutCreatedByNestedInput;
  workspaces?: Prisma.WorkspaceUncheckedUpdateManyWithoutCreatedByNestedInput;
};

/**
 * Count Type OrgUserCountOutputType
 */

export type OrgUserCountOutputType = {
  tags: number;
  workspaces: number;
  tasks: number;
};

export type OrgUserCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  tags?: boolean | OrgUserCountOutputTypeCountTagsArgs;
  workspaces?: boolean | OrgUserCountOutputTypeCountWorkspacesArgs;
  tasks?: boolean | OrgUserCountOutputTypeCountTasksArgs;
};

/**
 * OrgUserCountOutputType without action
 */
export type OrgUserCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUserCountOutputType
   */
  select?: Prisma.OrgUserCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * OrgUserCountOutputType without action
 */
export type OrgUserCountOutputTypeCountTagsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.TagWhereInput;
};

/**
 * OrgUserCountOutputType without action
 */
export type OrgUserCountOutputTypeCountWorkspacesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.WorkspaceWhereInput;
};

/**
 * OrgUserCountOutputType without action
 */
export type OrgUserCountOutputTypeCountTasksArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.TaskWhereInput;
};

export type OrgUserSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    id?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    tags?: boolean | Prisma.OrgUser$tagsArgs<ExtArgs>;
    workspaces?: boolean | Prisma.OrgUser$workspacesArgs<ExtArgs>;
    tasks?: boolean | Prisma.OrgUser$tasksArgs<ExtArgs>;
    _count?: boolean | Prisma.OrgUserCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["orgUser"]
>;

export type OrgUserSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    id?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["orgUser"]
>;

export type OrgUserSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    id?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["orgUser"]
>;

export type OrgUserSelectScalar = {
  userId?: boolean;
};

export type OrgUserOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<"userId", ExtArgs["result"]["orgUser"]>;
export type OrgUserInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  id?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  tags?: boolean | Prisma.OrgUser$tagsArgs<ExtArgs>;
  workspaces?: boolean | Prisma.OrgUser$workspacesArgs<ExtArgs>;
  tasks?: boolean | Prisma.OrgUser$tasksArgs<ExtArgs>;
  _count?: boolean | Prisma.OrgUserCountOutputTypeDefaultArgs<ExtArgs>;
};
export type OrgUserIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  id?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type OrgUserIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  id?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $OrgUserPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "OrgUser";
  objects: {
    id: Prisma.$UserPayload<ExtArgs>;
    tags: Prisma.$TagPayload<ExtArgs>[];
    workspaces: Prisma.$WorkspacePayload<ExtArgs>[];
    tasks: Prisma.$TaskPayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      userId: string;
    },
    ExtArgs["result"]["orgUser"]
  >;
  composites: {};
};

export type OrgUserGetPayload<
  S extends boolean | null | undefined | OrgUserDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$OrgUserPayload, S>;

export type OrgUserCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<OrgUserFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: OrgUserCountAggregateInputType | true;
};

export interface OrgUserDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["OrgUser"];
    meta: { name: "OrgUser" };
  };
  /**
   * Find zero or one OrgUser that matches the filter.
   * @param {OrgUserFindUniqueArgs} args - Arguments to find a OrgUser
   * @example
   * // Get one OrgUser
   * const orgUser = await prisma.orgUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrgUserFindUniqueArgs>(
    args: Prisma.SelectSubset<T, OrgUserFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__OrgUserClient<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one OrgUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrgUserFindUniqueOrThrowArgs} args - Arguments to find a OrgUser
   * @example
   * // Get one OrgUser
   * const orgUser = await prisma.orgUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrgUserFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, OrgUserFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__OrgUserClient<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first OrgUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgUserFindFirstArgs} args - Arguments to find a OrgUser
   * @example
   * // Get one OrgUser
   * const orgUser = await prisma.orgUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrgUserFindFirstArgs>(
    args?: Prisma.SelectSubset<T, OrgUserFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__OrgUserClient<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first OrgUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgUserFindFirstOrThrowArgs} args - Arguments to find a OrgUser
   * @example
   * // Get one OrgUser
   * const orgUser = await prisma.orgUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrgUserFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, OrgUserFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__OrgUserClient<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more OrgUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrgUsers
   * const orgUsers = await prisma.orgUser.findMany()
   *
   * // Get first 10 OrgUsers
   * const orgUsers = await prisma.orgUser.findMany({ take: 10 })
   *
   * // Only select the `userId`
   * const orgUserWithUserIdOnly = await prisma.orgUser.findMany({ select: { userId: true } })
   *
   */
  findMany<T extends OrgUserFindManyArgs>(
    args?: Prisma.SelectSubset<T, OrgUserFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a OrgUser.
   * @param {OrgUserCreateArgs} args - Arguments to create a OrgUser.
   * @example
   * // Create one OrgUser
   * const OrgUser = await prisma.orgUser.create({
   *   data: {
   *     // ... data to create a OrgUser
   *   }
   * })
   *
   */
  create<T extends OrgUserCreateArgs>(
    args: Prisma.SelectSubset<T, OrgUserCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__OrgUserClient<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many OrgUsers.
   * @param {OrgUserCreateManyArgs} args - Arguments to create many OrgUsers.
   * @example
   * // Create many OrgUsers
   * const orgUser = await prisma.orgUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends OrgUserCreateManyArgs>(
    args?: Prisma.SelectSubset<T, OrgUserCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many OrgUsers and returns the data saved in the database.
   * @param {OrgUserCreateManyAndReturnArgs} args - Arguments to create many OrgUsers.
   * @example
   * // Create many OrgUsers
   * const orgUser = await prisma.orgUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many OrgUsers and only return the `userId`
   * const orgUserWithUserIdOnly = await prisma.orgUser.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends OrgUserCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, OrgUserCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a OrgUser.
   * @param {OrgUserDeleteArgs} args - Arguments to delete one OrgUser.
   * @example
   * // Delete one OrgUser
   * const OrgUser = await prisma.orgUser.delete({
   *   where: {
   *     // ... filter to delete one OrgUser
   *   }
   * })
   *
   */
  delete<T extends OrgUserDeleteArgs>(
    args: Prisma.SelectSubset<T, OrgUserDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__OrgUserClient<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one OrgUser.
   * @param {OrgUserUpdateArgs} args - Arguments to update one OrgUser.
   * @example
   * // Update one OrgUser
   * const orgUser = await prisma.orgUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends OrgUserUpdateArgs>(
    args: Prisma.SelectSubset<T, OrgUserUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__OrgUserClient<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more OrgUsers.
   * @param {OrgUserDeleteManyArgs} args - Arguments to filter OrgUsers to delete.
   * @example
   * // Delete a few OrgUsers
   * const { count } = await prisma.orgUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends OrgUserDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, OrgUserDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more OrgUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrgUsers
   * const orgUser = await prisma.orgUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends OrgUserUpdateManyArgs>(
    args: Prisma.SelectSubset<T, OrgUserUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more OrgUsers and returns the data updated in the database.
   * @param {OrgUserUpdateManyAndReturnArgs} args - Arguments to update many OrgUsers.
   * @example
   * // Update many OrgUsers
   * const orgUser = await prisma.orgUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more OrgUsers and only return the `userId`
   * const orgUserWithUserIdOnly = await prisma.orgUser.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends OrgUserUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, OrgUserUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one OrgUser.
   * @param {OrgUserUpsertArgs} args - Arguments to update or create a OrgUser.
   * @example
   * // Update or create a OrgUser
   * const orgUser = await prisma.orgUser.upsert({
   *   create: {
   *     // ... data to create a OrgUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrgUser we want to update
   *   }
   * })
   */
  upsert<T extends OrgUserUpsertArgs>(
    args: Prisma.SelectSubset<T, OrgUserUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__OrgUserClient<
    runtime.Types.Result.GetResult<
      Prisma.$OrgUserPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of OrgUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgUserCountArgs} args - Arguments to filter OrgUsers to count.
   * @example
   * // Count the number of OrgUsers
   * const count = await prisma.orgUser.count({
   *   where: {
   *     // ... the filter for the OrgUsers we want to count
   *   }
   * })
   **/
  count<T extends OrgUserCountArgs>(
    args?: Prisma.Subset<T, OrgUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], OrgUserCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a OrgUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends OrgUserAggregateArgs>(
    args: Prisma.Subset<T, OrgUserAggregateArgs>,
  ): Prisma.PrismaPromise<GetOrgUserAggregateType<T>>;

  /**
   * Group by OrgUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends OrgUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrgUserGroupByArgs["orderBy"] }
      : { orderBy?: OrgUserGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, OrgUserGroupByArgs, OrderByArg> &
      InputErrors,
  ): {} extends InputErrors
    ? GetOrgUserGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the OrgUser model
   */
  readonly fields: OrgUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrgUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrgUserClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  id<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  tags<T extends Prisma.OrgUser$tagsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.OrgUser$tagsArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$TagPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  workspaces<T extends Prisma.OrgUser$workspacesArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.OrgUser$workspacesArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$WorkspacePayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  tasks<T extends Prisma.OrgUser$tasksArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.OrgUser$tasksArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$TaskPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the OrgUser model
 */
export interface OrgUserFieldRefs {
  readonly userId: Prisma.FieldRef<"OrgUser", "String">;
}

// Custom InputTypes
/**
 * OrgUser findUnique
 */
export type OrgUserFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * Filter, which OrgUser to fetch.
   */
  where: Prisma.OrgUserWhereUniqueInput;
};

/**
 * OrgUser findUniqueOrThrow
 */
export type OrgUserFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * Filter, which OrgUser to fetch.
   */
  where: Prisma.OrgUserWhereUniqueInput;
};

/**
 * OrgUser findFirst
 */
export type OrgUserFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * Filter, which OrgUser to fetch.
   */
  where?: Prisma.OrgUserWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OrgUsers to fetch.
   */
  orderBy?:
    | Prisma.OrgUserOrderByWithRelationInput
    | Prisma.OrgUserOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OrgUsers.
   */
  cursor?: Prisma.OrgUserWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OrgUsers from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OrgUsers.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OrgUsers.
   */
  distinct?: Prisma.OrgUserScalarFieldEnum | Prisma.OrgUserScalarFieldEnum[];
};

/**
 * OrgUser findFirstOrThrow
 */
export type OrgUserFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * Filter, which OrgUser to fetch.
   */
  where?: Prisma.OrgUserWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OrgUsers to fetch.
   */
  orderBy?:
    | Prisma.OrgUserOrderByWithRelationInput
    | Prisma.OrgUserOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OrgUsers.
   */
  cursor?: Prisma.OrgUserWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OrgUsers from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OrgUsers.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OrgUsers.
   */
  distinct?: Prisma.OrgUserScalarFieldEnum | Prisma.OrgUserScalarFieldEnum[];
};

/**
 * OrgUser findMany
 */
export type OrgUserFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * Filter, which OrgUsers to fetch.
   */
  where?: Prisma.OrgUserWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OrgUsers to fetch.
   */
  orderBy?:
    | Prisma.OrgUserOrderByWithRelationInput
    | Prisma.OrgUserOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing OrgUsers.
   */
  cursor?: Prisma.OrgUserWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OrgUsers from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OrgUsers.
   */
  skip?: number;
  distinct?: Prisma.OrgUserScalarFieldEnum | Prisma.OrgUserScalarFieldEnum[];
};

/**
 * OrgUser create
 */
export type OrgUserCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * The data needed to create a OrgUser.
   */
  data: Prisma.XOR<
    Prisma.OrgUserCreateInput,
    Prisma.OrgUserUncheckedCreateInput
  >;
};

/**
 * OrgUser createMany
 */
export type OrgUserCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many OrgUsers.
   */
  data: Prisma.OrgUserCreateManyInput | Prisma.OrgUserCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * OrgUser createManyAndReturn
 */
export type OrgUserCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * The data used to create many OrgUsers.
   */
  data: Prisma.OrgUserCreateManyInput | Prisma.OrgUserCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * OrgUser update
 */
export type OrgUserUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * The data needed to update a OrgUser.
   */
  data: Prisma.XOR<
    Prisma.OrgUserUpdateInput,
    Prisma.OrgUserUncheckedUpdateInput
  >;
  /**
   * Choose, which OrgUser to update.
   */
  where: Prisma.OrgUserWhereUniqueInput;
};

/**
 * OrgUser updateMany
 */
export type OrgUserUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update OrgUsers.
   */
  data: Prisma.XOR<
    Prisma.OrgUserUpdateManyMutationInput,
    Prisma.OrgUserUncheckedUpdateManyInput
  >;
  /**
   * Filter which OrgUsers to update
   */
  where?: Prisma.OrgUserWhereInput;
  /**
   * Limit how many OrgUsers to update.
   */
  limit?: number;
};

/**
 * OrgUser updateManyAndReturn
 */
export type OrgUserUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * The data used to update OrgUsers.
   */
  data: Prisma.XOR<
    Prisma.OrgUserUpdateManyMutationInput,
    Prisma.OrgUserUncheckedUpdateManyInput
  >;
  /**
   * Filter which OrgUsers to update
   */
  where?: Prisma.OrgUserWhereInput;
  /**
   * Limit how many OrgUsers to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * OrgUser upsert
 */
export type OrgUserUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * The filter to search for the OrgUser to update in case it exists.
   */
  where: Prisma.OrgUserWhereUniqueInput;
  /**
   * In case the OrgUser found by the `where` argument doesn't exist, create a new OrgUser with this data.
   */
  create: Prisma.XOR<
    Prisma.OrgUserCreateInput,
    Prisma.OrgUserUncheckedCreateInput
  >;
  /**
   * In case the OrgUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.OrgUserUpdateInput,
    Prisma.OrgUserUncheckedUpdateInput
  >;
};

/**
 * OrgUser delete
 */
export type OrgUserDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
  /**
   * Filter which OrgUser to delete.
   */
  where: Prisma.OrgUserWhereUniqueInput;
};

/**
 * OrgUser deleteMany
 */
export type OrgUserDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which OrgUsers to delete
   */
  where?: Prisma.OrgUserWhereInput;
  /**
   * Limit how many OrgUsers to delete.
   */
  limit?: number;
};

/**
 * OrgUser.tags
 */
export type OrgUser$tagsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Tag
   */
  select?: Prisma.TagSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Tag
   */
  omit?: Prisma.TagOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagInclude<ExtArgs> | null;
  where?: Prisma.TagWhereInput;
  orderBy?:
    | Prisma.TagOrderByWithRelationInput
    | Prisma.TagOrderByWithRelationInput[];
  cursor?: Prisma.TagWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.TagScalarFieldEnum | Prisma.TagScalarFieldEnum[];
};

/**
 * OrgUser.workspaces
 */
export type OrgUser$workspacesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null;
  where?: Prisma.WorkspaceWhereInput;
  orderBy?:
    | Prisma.WorkspaceOrderByWithRelationInput
    | Prisma.WorkspaceOrderByWithRelationInput[];
  cursor?: Prisma.WorkspaceWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.WorkspaceScalarFieldEnum
    | Prisma.WorkspaceScalarFieldEnum[];
};

/**
 * OrgUser.tasks
 */
export type OrgUser$tasksArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null;
  where?: Prisma.TaskWhereInput;
  orderBy?:
    | Prisma.TaskOrderByWithRelationInput
    | Prisma.TaskOrderByWithRelationInput[];
  cursor?: Prisma.TaskWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?: Prisma.TaskScalarFieldEnum | Prisma.TaskScalarFieldEnum[];
};

/**
 * OrgUser without action
 */
export type OrgUserDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the OrgUser
   */
  select?: Prisma.OrgUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OrgUser
   */
  omit?: Prisma.OrgUserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgUserInclude<ExtArgs> | null;
};
