import "@/lib/ui/styles/index.scss";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/charts/styles.css";
import "@mantine/tiptap/styles.css";
import type { Metadata } from "next";
import { Suspense } from "react";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import Script from "next/script";
import Providers from "@/lib/ui/components/providers/Providers";

export const metadata: Metadata = {
  title: "Nextjs Express Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="" {...mantineHtmlProps}>
      <head>
        <Suspense>
          <Script strategy="beforeInteractive" src="/js/setThemeScript.js" />
          <ColorSchemeScript />
        </Suspense>
      </head>
      <body>
        <Providers>
          {children}
          <Notifications autoClose={3000} />
        </Providers>
      </body>
    </html>
  );
}
